language: python
python:
    - "3.5"

install:
    - pip install sphinx travis-sphinx sphinx_rtd_theme sphinxcontrib-blockdiag

script:
    - travis-sphinx --source=source build

after_success:
    - travis-sphinx deploy
