language: python
python:
    - "3.5"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y otf-ipafont-gothic

install:
    - pip install sphinx travis-sphinx sphinx_rtd_theme sphinxcontrib-blockdiag

script:
    - travis-sphinx --source=source build

after_success:
    - travis-sphinx deploy
